#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-particle-pthreads16
#SBATCH -o auto-particle-pthreads16.stdout
#SBATCH -n 16         
#SBATCH -p RM
#SBATCH -t 00:10:00
#SBATCH -N 1         
     
rm pthreads_sum.txt
./serial -n 500 -no -s pthreads_sum.txt
./pthreads -p 1 -n 500 -no -s pthreads_sum.txt
./pthreads -p 2 -n 500 -no -s pthreads_sum.txt
./pthreads -p 4 -n 500 -no -s pthreads_sum.txt
./pthreads -p 8 -n 500 -no -s pthreads_sum.txt
./pthreads -p 16 -n 500 -no -s pthreads_sum.txt
./pthreads -p 2 -n 1000 -no -s pthreads_sum.txt
./pthreads -p 4 -n 2000 -no -s pthreads_sum.txt
./pthreads -p 8 -n 4000 -no -s pthreads_sum.txt
./pthreads -p 16 -n 8000 -no -s pthreads_sum.txt
./autograder -v pthreads -s pthreads_sum.txt
