#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J particle-mpi16
#SBATCH -o particle-mpi16.stdout
#SBATCH -N 16
#SBATCH -n 16         
#SBATCH -p RM
#SBATCH -t 00:10:00     
mpirun -n 16 ./mpi -n 1000 -o mpi.txt
